### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thatprogrammer1** [thatprogrammer1/stacking-robot#6]
Compiling a list of things that probably should be worked on to get a decent full-stack system working 

### Environment
- [ ] Add colors to prisms
- [ ] Get prisms working
- [x] Fix prisms sometimes falling out of the camera sight at init

### Perception
- [x] Figure out a non-cheaty way to do the segmentation #7 

### Grasping
- [ ] Grasp in the center of blocks, rather than the edges 
  - I think this relies on #7, but maybe there's a way that I'm not thinking of?

### Placing
- [x] Place so COM of prism is at the center of the stacking cylinder
  - Estimating COM can be done with #7, or possibly it can be done by measuring the torques on the joints as Tedrake mentioned?
- [ ] Place on the stack softly, instead of pushing down on the stack
  - I can think of 2 approaches: 
    -  1. Estimate the bottom of the block, and just plan so that the bottom of the block perfectly aligns with the top of the stack.
    - 2. Force control something something - descend until you feel the block touch the stack

### Planning
- [ ] Figure out what to do when blocks spawn in the stacking cylinder 
  - Perhaps just choose a stacking cylinder at start that doesn't intersect with other objects? Or we can have a clearing state for any blocks that are not perfectly in the cylinder?
